# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_date', models.DateField()),
                ('tweet_username', models.CharField(max_length=50)),
                ('tweet_text', models.CharField(max_length=200)),
                ('session_id', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Tweets',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('friends', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('session_id', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
